### PR TITLE
fix: fixed broken link from list

### LINKED ISSUE #1059: HTTP 404 Link README -> Web Server
Hey! This link navigates to 404:

image

### PR DESCRIPTION
**Pull request by davayd**
closes #1059

### CODE REVIEW

**Comment by davayd** [comment]
@patrickreisx  great catch! thank you, i've updated PR

**Review by GamerDevIND — COMMENTED** [review]
.

**Review by Debagnik — APPROVED** [review]
Lgtm!

**Comment by rohitpaulk** [comment]
Thank you for updating this!

**Pull request merged**
