### PR TITLE
delete a useless item

### PR DESCRIPTION
**Pull request by fake-rookie**
that item is nothing.

### CODE REVIEW

**Comment by bweston92** [comment]
It links to the table of contents, them headers show more content.

**Comment by fake-rookie** [comment]
Yes. that is a contents.
BUT

Did you SEE some USEFUL & SPECIFIC contents????

**Comment by MuhammedZakir** [comment]
From that link:
```
Table of Contents
 
[1 – What are key-value stores, and why implement one?](http://codecapsule.com/2012/11/07/ikvs-part-1-what-are-key-value-stores-and-why-implement-one/)

    1.1 – A quick overview of key-value stores
    1.2 – Key-value stores versus relational databases
    1.3 – Why implement a key-value store
    1.4 – The plan

[2 – Using existing key-value stores as models](http://codecapsule.com/2012/12/03/implementing-a-key-value-store-part-2-using-existing-key-value-stores-as-models/)

    2.1 – Not reinventing the wheel
    2.2 – Model candidates and selection criteria
    2.3 – Overview of the selected key-value stores

[3 – Comparative Analysis of the Architectures of Kyoto Cabinet and LevelDB](http://codecapsule.com/2012/12/30/implementing-a-key-value-store-part-3-comparative-analysis-of-the-architectures-of-kyoto-cabinet-and-leveldb/)

    3.1 – Intent and methodology of this architecture analysis
    3.2 – Overview of the Components of a Key-Value Store
    3.3 – Structural and conceptual analysis of Kyoto Cabinet and LevelDB
    3.4 – Code review

[4 – API Design](http://codecapsule.com/2013/04/03/implementing-a-key-value-store-part-4-api-design/)

    4.1 – General principles for API design
    4.2 – Defining the functionalities for the public API of KingDB
    4.3 – Comparing the APIs of existing databases

[5 – Hash table implementations](http://codecapsule.com/2013/05/13/implementing-a-key-value-store-part-5-hash-table-implementations/)

    5.1 – Hash tables
    5.2 – Implementations

[6 – Open-Addressing Hash Tables](http://codecapsule.com/2014/05/07/implementing-a-key-value-store-part-6-open-addressing-hash-tables/)

    6.1 – Open-addressing hash tables
    6.2 – Metrics
    6.3 – Experimental Protocol
    6.4 – Results and Discussion

[7 – Optimizing Data Structures for SSDs](http://codecapsule.com/2014/10/18/implementing-a-key-value-store-part-7-optimizing-data-structures-for-ssds/)

    7.1 – Fast data structures on SSDs
    7.2 – File I/O optimizations
    7.3 – Done is better than perfect

[8 – Architecture of KingDB](http://codecapsule.com/2015/05/25/implementing-a-key-value-store-part-8-architecture-of-kingdb/)

[9 – Data Format and Memory Management in KingDB](http://codecapsule.com/2015/08/03/implementing-a-key-value-store-part-9-data-format-and-memory-management-in-kingdb/)

[10 – High-Performance Networking: KingServer vs. Nginx](http://codecapsule.com/2016/07/21/implementing-a-key-value-store-part-10-high-performance-networking-kingserver-vs-nginx/)

Coming next, the final article:

11 – Mistakes and learnings
```

> Did you SEE some USEFUL & SPECIFIC contents????

Or, are you telling that, that tutorial is useless?

**Comment by stickyfingies** [comment]
Struggling to understand the energy here...
It's a useful link, even if it shows little code. At the very least, I could learn something from it.

**Comment by fake-rookie** [comment]
> Struggling to understand the energy here... It's a useful link, even if it shows little code. At the very least, I could learn something from it.

First of All, it not amount of code things.

2nd, Write a KEY-VALUE DATABASE by theses contents.
show it to me.
I think ONE DAY is ENOUGH TIME, RIGHT?

**Comment by arcanosam** [comment]
@stickyfingies I think that this link not fullfill the purpose of this repo, because here the purpose it's to learn by doing, building. That link it's just a journal of author's experiencie about this subject. In the end you couldn't really 'duplicate' it byt doing it yourself. I think that is the problem.

**Comment by fake-rookie** [comment]
> @stickyfingies I think that this link not fullfill the purpose of this repo, because here the purpose it's to learn by doing, building. That link it's just a journal of author's experiencie about this subject. In the end you couldn't really 'duplicate' it byt doing it yourself. I think that is the problem.

Good man.
You **GOT** it.

**Pull request merged**
